services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - certbot
    networks:
      - retrip

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'

  spring_blue:
    image: rt3310/retrip:latest
    container_name: spring_blue
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - retrip
    volumes:
      - ./:/app/local
      - /var/log/retrip-log:/var/log/retrip-log

  spring_green:
    image: rt3310/retrip:latest
    container_name: spring_green
    restart: on-failure:3
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    networks:
      - retrip
    volumes:
      - ./:/app/local
      - /var/log/retrip-log:/var/log/retrip-log

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.prod.yml:/etc/promtail/config.yml
      - /var/log/retrip-log:/var/log/app
      - /var/lib/promtail:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - retrip

  mysql:
    image: mysql:8.0.44-debian
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    networks:
      - retrip

networks:
  retrip:
    driver: bridge