spring:
  config:
    activate:
      on-profile: dev
    import: aws-secretsmanager:dev/retrip

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: validate

  h2:
    console:
      enabled: true

  cloud:
    gcp:
      storage:
        bucket: ${GCP_BUCKET_NAME}
        project-id: ${GCP_PROJECT_ID}

logging:
  level:
    com.vibetrip: debug

jwt:
  secret-key: ${JWT_SECRET_KEY}

app:
  cache:
    configs:
      appleKeys:
        ttl: 24h
        max-size: 10